name: 'build-test'
on: # rebuild any PRs and main branch changes
  schedule:
    - cron: '0 * * * *'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
